#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox-guzzii"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    vimcompatible = true
    default_indent = 4
    enable_vimfiler_welcome = false
    enable_guicolors = true
    guifont = "Iosevka Nerd Font:h14"

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    statusline_left_sections = [
        'winnr',
        'filename',
        'version control info'
    ]
    statusline_right_sections = [
        'cursorpos',
        'percentage'
    ]

    buffer_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    
    autocomplete_parens = false
    autocomplete_method = "coc"
    snippet_engine = "ultisnips"

    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

[[layers]]
  name = "ui"
  enable_sidebar = false

[[layers]]
  name = "core#statusline"
  enable = true

[[layers]]
  name = "core#tabline"
  enable = true

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = 'checkers'
    enable = false

[[layers]]
    name = 'lang#python'

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = "fzf"

[[layers]]
    name = "tmux"

[[layers]]
    name = "VersionControl"

[[layers]]
    name = 'git'
    git-plugin = 'fugitive'

[[layers]]
    name = 'github'

[[custom_plugins]]
    name = "jiangmiao/auto-pairs"

[[custom_plugins]]
    name = "Guzzii/python-syntax"
    merged = false

[[custom_plugins]]
    name = 'Guzzii/vim-two-firewatch'
    merged = false

[[custom_plugins]]
    name = 'Guzzii/gruvbox'
    merged = false

# [[custom_plugins]]
    # name = 'roxma/nvim-yarp'
#
# [[custom_plugins]]
    # name = 'roxma/vim-hug-neovim-rpc'
